### ISSUE TITLE
[1.18.2] Fly Boat, Fly

### ISSUE THREAD

**Issue by itsdinkd** [JDKDigital/jumpboat#2]
You can spam jump in a boat and literally go as high as you want.

**Comment by JaisDK** [comment]
I can't reproduce it. Which version of the mod are you on?

**Comment by itsdinkd** [comment]
The version that was latest when I opened this almost 2 months ago

**Comment by JaisDK** [comment]
GH didn't want to inform me of the opened issue. I can't reproduce it though, repeatedly jumping both on land and in water does not send me flying.
